spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      name: adm
      profile: local
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
server:
  port: 8089